CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Funcionarios" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" text NOT NULL,
    "Cpf" character varying(11) NOT NULL,
    "Situacao" character(1) NOT NULL,
    "DataAlteracao" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_Funcionarios" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_Funcionario_Cpf" ON "Funcionarios" ("Cpf");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240907210746_Criando banco de dados e tabela Funcionario', '6.0.22');

COMMIT;

START TRANSACTION;

CREATE TABLE "TicketsEntregue" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Quantidade" integer NOT NULL,
    "Situacao" character(1) NOT NULL,
    "DataEntrega" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "FuncionarioId" integer NOT NULL,
    CONSTRAINT "PK_TicketsEntregue" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TicketsEntregue_Funcionarios_FuncionarioId" FOREIGN KEY ("FuncionarioId") REFERENCES "Funcionarios" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_TicketsEntregue_FuncionarioId" ON "TicketsEntregue" ("FuncionarioId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240909011355_Incluindo tabela de ticketEntregue', '6.0.22');

COMMIT;

